-- Drop old databases and user if they exist
DROP DATABASE IF EXISTS ${AUTH_DB};
DROP DATABASE IF EXISTS ${WORLD_DB};
DROP DATABASE IF EXISTS ${CHARACTER_DB};
DROP DATABASE IF EXISTS ${PLAYERBOTS_DB};
DROP USER IF EXISTS '${SERVER_DB_USER}'@'%';

-- Create fresh databases
CREATE DATABASE ${AUTH_DB};
CREATE DATABASE ${WORLD_DB};
CREATE DATABASE ${CHARACTER_DB};
CREATE DATABASE ${PLAYERBOTS_DB};

-- Recreate user and grant access
CREATE USER '${SERVER_DB_USER}'@'%' IDENTIFIED BY '${SERVER_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${AUTH_DB}.* TO '${SERVER_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON ${WORLD_DB}.* TO '${SERVER_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON ${CHARACTER_DB}.* TO '${SERVER_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON ${PLAYERBOTS_DB}.* TO '${SERVER_DB_USER}'@'%';
FLUSH PRIVILEGES;