-- Drops existing databases and user for a clean setup.

DROP DATABASE IF EXISTS ${AUTH_DB};
DROP DATABASE IF EXISTS ${WORLD_DB};
DROP DATABASE IF EXISTS ${CHARACTER_DB};
DROP DATABASE IF EXISTS ${PLAYERBOTS_DB};
DROP USER IF EXISTS '${SERVER_DB_USER}'@'%';

FLUSH PRIVILEGES;